### ISSUE TITLE
Coming soon

### ISSUE THREAD

**Issue by anoop-ananthan** [anoop-ananthan/bhi_punchlog#7]
Calculator

![coming_soon](https://user-images.githubusercontent.com/40450822/76727432-08d3f100-677a-11ea-8d66-72b866d16955.png)

**Comment by bhi-sudesh** [comment]
![comming-soon](https://user-images.githubusercontent.com/40426616/76728331-6d904b00-677c-11ea-9ad3-82e36a6828c8.png)
transparent background image

**Comment by anoop-ananthan** [comment]
thanks
